server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rabc?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp